"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/suno/tasks"

ENDPOINTS = {
    "suno_generate_audios": {
        "method": "POST",
        "path": "/suno/audios",
        "operation": "generate",
        "schema": {
            "type": "object",
            "properties": {
                "lyric": {"type": "string"},
                "model": {
                    "enum": [
                        "chirp-v6",
                        "chirp-v6-wild",
                        "chirp-v6-mini",
                        "chirp-v5-5",
                        "chirp-v5",
                        "chirp-v4-5-plus",
                        "chirp-v4-5",
                        "chirp-v4",
                        "chirp-v3-5",
                        "chirp-v3-0",
                    ],
                    "type": "string",
                },
                "max_mode": {"type": "boolean"},
                "variety": {"enum": ["off", "normal", "high", "extra", "max"], "type": "string"},
                "style": {"type": "string"},
                "variation_category": {"type": "string", "enum": ["high", "normal", "subtle"]},
                "title": {"type": "string"},
                "action": {
                    "enum": [
                        "generate",
                        "extend",
                        "upload_extend",
                        "upload_cover",
                        "concat",
                        "cover",
                        "artist_consistency",
                        "artist_consistency_vox",
                        "stems",
                        "all_stems",
                        "add_stem",
                        "extract_stem",
                        "sounds",
                        "adjust_speed",
                        "replace_section",
                        "underpainting",
                        "overpainting",
                        "remaster",
                        "mashup",
                        "samples",
                        "inspo",
                    ],
                    "type": "string",
                },
                "custom": {"type": "boolean"},
                "prompt": {"type": "string", "additionalProperties": True},
                "lyric_prompt": {"type": "string"},
                "audio_id": {"type": "string"},
                "stem_type": {
                    "type": "string",
                    "enum": [
                        "vocals",
                        "backing_vocals",
                        "drums",
                        "bass",
                        "guitar",
                        "keyboard",
                        "percussion",
                        "strings",
                        "synth",
                        "fx",
                        "brass",
                        "woodwinds",
                    ],
                },
                "audio_format": {"type": "string", "enum": ["mp3"]},
                "sound": {"type": "string"},
                "sound_type": {"type": "string", "enum": ["one-shot", "loop"]},
                "bpm": {"type": "integer", "minimum": 1, "maximum": 300},
                "key": {"type": "string"},
                "speed_multiplier": {"type": "number", "minimum": 0.25, "maximum": 4},
                "keep_pitch": {"type": "boolean"},
                "mashup_audio_ids": {"type": "array", "items": {"type": "string"}},
                "audio_urls": {
                    "type": "array",
                    "items": {"type": "string", "pattern": "^https?://"},
                    "minItems": 1,
                    "maxItems": 4,
                },
                "weirdness": {"type": "number", "minimum": 0, "maximum": 1},
                "persona_id": {"type": "string"},
                "overpainting_start": {"type": "number"},
                "overpainting_end": {"type": "number"},
                "samples_start": {"type": "number"},
                "samples_end": {"type": "number"},
                "underpainting_start": {"type": "number"},
                "underpainting_end": {"type": "number"},
                "continue_at": {"type": "number"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
                "instrumental": {"type": "boolean"},
                "vocal_gender": {"type": "string", "enum": ["f", "m"]},
                "negative_tags": {"type": "string"},
                "style_influence": {"type": "number", "minimum": 0, "maximum": 1},
                "audio_weight": {"type": "number", "minimum": 0, "maximum": 1},
                "duration": {"type": "integer", "minimum": 10, "maximum": 360},
                "replace_section_end": {"type": "number"},
                "replace_section_result_mode": {
                    "type": "string",
                    "enum": ["candidates", "full_song"],
                },
                "replace_section_start": {"type": "number"},
            },
        },
        "properties": {
            "lyric": {"type": "string"},
            "model": {
                "enum": [
                    "chirp-v6",
                    "chirp-v6-wild",
                    "chirp-v6-mini",
                    "chirp-v5-5",
                    "chirp-v5",
                    "chirp-v4-5-plus",
                    "chirp-v4-5",
                    "chirp-v4",
                    "chirp-v3-5",
                    "chirp-v3-0",
                ],
                "type": "string",
            },
            "max_mode": {"type": "boolean"},
            "variety": {"enum": ["off", "normal", "high", "extra", "max"], "type": "string"},
            "style": {"type": "string"},
            "variation_category": {"type": "string", "enum": ["high", "normal", "subtle"]},
            "title": {"type": "string"},
            "action": {
                "enum": [
                    "generate",
                    "extend",
                    "upload_extend",
                    "upload_cover",
                    "concat",
                    "cover",
                    "artist_consistency",
                    "artist_consistency_vox",
                    "stems",
                    "all_stems",
                    "add_stem",
                    "extract_stem",
                    "sounds",
                    "adjust_speed",
                    "replace_section",
                    "underpainting",
                    "overpainting",
                    "remaster",
                    "mashup",
                    "samples",
                    "inspo",
                ],
                "type": "string",
            },
            "custom": {"type": "boolean"},
            "prompt": {"type": "string", "additionalProperties": True},
            "lyric_prompt": {"type": "string"},
            "audio_id": {"type": "string"},
            "stem_type": {
                "type": "string",
                "enum": [
                    "vocals",
                    "backing_vocals",
                    "drums",
                    "bass",
                    "guitar",
                    "keyboard",
                    "percussion",
                    "strings",
                    "synth",
                    "fx",
                    "brass",
                    "woodwinds",
                ],
            },
            "audio_format": {"type": "string", "enum": ["mp3"]},
            "sound": {"type": "string"},
            "sound_type": {"type": "string", "enum": ["one-shot", "loop"]},
            "bpm": {"type": "integer", "minimum": 1, "maximum": 300},
            "key": {"type": "string"},
            "speed_multiplier": {"type": "number", "minimum": 0.25, "maximum": 4},
            "keep_pitch": {"type": "boolean"},
            "mashup_audio_ids": {"type": "array", "items": {"type": "string"}},
            "audio_urls": {
                "type": "array",
                "items": {"type": "string", "pattern": "^https?://"},
                "minItems": 1,
                "maxItems": 4,
            },
            "weirdness": {"type": "number", "minimum": 0, "maximum": 1},
            "persona_id": {"type": "string"},
            "overpainting_start": {"type": "number"},
            "overpainting_end": {"type": "number"},
            "samples_start": {"type": "number"},
            "samples_end": {"type": "number"},
            "underpainting_start": {"type": "number"},
            "underpainting_end": {"type": "number"},
            "continue_at": {"type": "number"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
            "instrumental": {"type": "boolean"},
            "vocal_gender": {"type": "string", "enum": ["f", "m"]},
            "negative_tags": {"type": "string"},
            "style_influence": {"type": "number", "minimum": 0, "maximum": 1},
            "audio_weight": {"type": "number", "minimum": 0, "maximum": 1},
            "duration": {"type": "integer", "minimum": 10, "maximum": 360},
            "replace_section_end": {"type": "number"},
            "replace_section_result_mode": {"type": "string", "enum": ["candidates", "full_song"]},
            "replace_section_start": {"type": "number"},
        },
        "parameters": [],
        "defaults": {
            "model": "chirp-v6",
            "custom": False,
            "instrumental": False,
            "action": "generate",
        },
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_generate_lyrics": {
        "method": "POST",
        "path": "/suno/lyrics",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["prompt", "model"],
            "properties": {
                "model": {"enum": ["default", "remi-v1"], "type": "string"},
                "prompt": {"type": "string", "additionalProperties": True},
            },
        },
        "properties": {
            "model": {"enum": ["default", "remi-v1"], "type": "string"},
            "prompt": {"type": "string", "additionalProperties": True},
        },
        "parameters": [],
        "defaults": {"model": "default"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_upload_reference_audio": {
        "method": "POST",
        "path": "/suno/upload",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_url"],
            "properties": {
                "audio_url": {"type": "string"},
                "mode": {"type": "string", "enum": ["standard", "enhanced"]},
                "name": {"type": "string", "minLength": 1, "maxLength": 100},
                "callback_url": {"type": "string", "format": "uri"},
            },
        },
        "properties": {
            "audio_url": {"type": "string"},
            "mode": {"type": "string", "enum": ["standard", "enhanced"]},
            "name": {"type": "string", "minLength": 1, "maxLength": 100},
            "callback_url": {"type": "string", "format": "uri"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_get_mp4": {
        "method": "POST",
        "path": "/suno/mp4",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_id"],
            "properties": {"audio_id": {"type": "string"}},
        },
        "properties": {"audio_id": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_get_mp3": {
        "method": "POST",
        "path": "/suno/mp3",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_id"],
            "properties": {
                "audio_id": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "audio_id": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_get_wav": {
        "method": "POST",
        "path": "/suno/wav",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_id"],
            "properties": {
                "audio_id": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "audio_id": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_get_midi": {
        "method": "POST",
        "path": "/suno/midi",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_id"],
            "properties": {
                "audio_id": {"type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "audio_id": {"type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_get_timing": {
        "method": "POST",
        "path": "/suno/timing",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_id"],
            "properties": {"audio_id": {"type": "string"}},
        },
        "properties": {"audio_id": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_create_vox_audio": {
        "method": "POST",
        "path": "/suno/vox",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_id", "vocal_start", "vocal_end"],
            "properties": {
                "audio_id": {"type": "string"},
                "vocal_start": {"type": "number", "minimum": 0},
                "vocal_end": {"type": "number", "exclusiveMinimum": 0},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "audio_id": {"type": "string"},
            "vocal_start": {"type": "number", "minimum": 0},
            "vocal_end": {"type": "number", "exclusiveMinimum": 0},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_enhance_style": {
        "method": "POST",
        "path": "/suno/style",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["prompt"],
            "properties": {"prompt": {"type": "string"}},
        },
        "properties": {"prompt": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_mashup_lyrics": {
        "method": "POST",
        "path": "/suno/mashup-lyrics",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["lyrics_a", "lyrics_b"],
            "properties": {"lyrics_a": {"type": "string"}, "lyrics_b": {"type": "string"}},
        },
        "properties": {"lyrics_a": {"type": "string"}, "lyrics_b": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_create_voice": {
        "method": "POST",
        "path": "/suno/voices",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_url"],
            "properties": {
                "audio_url": {"type": "string"},
                "name": {"type": "string"},
                "description": {"type": "string"},
            },
        },
        "properties": {
            "audio_url": {"type": "string"},
            "name": {"type": "string"},
            "description": {"type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "suno_create_persona": {
        "method": "POST",
        "path": "/suno/persona",
        "operation": "request",
        "schema": {
            "type": "object",
            "required": ["audio_id", "name"],
            "properties": {
                "name": {"type": "string"},
                "audio_id": {"type": "string"},
                "vox_audio_id": {"type": "string"},
                "vocal_start": {"type": "number"},
                "vocal_end": {"type": "number"},
                "description": {"type": "string"},
            },
        },
        "properties": {
            "name": {"type": "string"},
            "audio_id": {"type": "string"},
            "vox_audio_id": {"type": "string"},
            "vocal_start": {"type": "number"},
            "vocal_end": {"type": "number"},
            "description": {"type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_list_personas": {
        "method": "GET",
        "path": "/suno/persona",
        "operation": "request",
        "schema": {"type": "object", "properties": {}},
        "properties": {},
        "parameters": [
            {"in": "query", "name": "user_id", "schema": {"type": "string"}, "required": True},
            {"in": "query", "name": "limit", "schema": {"type": "integer"}, "required": False},
            {"in": "query", "name": "offset", "schema": {"type": "integer"}, "required": False},
        ],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "suno_delete_persona": {
        "method": "DELETE",
        "path": "/suno/persona",
        "operation": "request",
        "schema": {"type": "object", "properties": {}},
        "properties": {},
        "parameters": [
            {"in": "query", "name": "persona_id", "schema": {"type": "string"}, "required": True},
            {"in": "query", "name": "user_id", "schema": {"type": "string"}, "required": False},
        ],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
        "destructive": True,
    },
    "suno_custom_models": {
        "method": "POST",
        "path": "/suno/custom-models",
        "operation": "request",
        "schema": {
            "oneOf": [
                {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["action", "name", "audio_urls"],
                    "properties": {
                        "action": {"type": "string", "enum": ["create"]},
                        "name": {"type": "string", "minLength": 1, "maxLength": 100},
                        "audio_urls": {
                            "type": "array",
                            "minItems": 6,
                            "maxItems": 24,
                            "uniqueItems": True,
                            "items": {"type": "string", "format": "uri", "pattern": "^https://"},
                        },
                        "callback_url": {"type": "string", "format": "uri", "pattern": "^https://"},
                    },
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["action", "id"],
                    "properties": {
                        "action": {"type": "string", "enum": ["generate"]},
                        "id": {"type": "string", "format": "uuid"},
                        "lyric": {"type": "string"},
                        "lyric_prompt": {"type": "string"},
                        "style": {"type": "string"},
                        "negative_tags": {"type": "string"},
                        "title": {"type": "string"},
                        "instrumental": {"type": "boolean"},
                        "vocal_gender": {"type": "string", "enum": ["f", "m"]},
                        "weirdness": {"type": "number", "minimum": 0, "maximum": 1},
                        "style_influence": {"type": "number", "minimum": 0, "maximum": 1},
                        "duration": {"type": "integer"},
                        "async": {"type": "boolean"},
                        "callback_url": {"type": "string", "format": "uri", "pattern": "^https://"},
                    },
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["action", "id"],
                    "properties": {
                        "action": {"type": "string", "enum": ["retrieve"]},
                        "id": {"type": "string", "format": "uuid"},
                    },
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["action"],
                    "properties": {
                        "action": {"type": "string", "enum": ["retrieve_batch"]},
                        "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                        "offset": {"type": "integer", "minimum": 0},
                        "status": {
                            "type": "string",
                            "enum": [
                                "queued",
                                "uploading",
                                "training",
                                "ready",
                                "failed",
                                "archived",
                            ],
                        },
                    },
                },
                {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["action", "id"],
                    "properties": {
                        "action": {"type": "string", "enum": ["delete"]},
                        "id": {"type": "string", "format": "uuid"},
                    },
                },
            ],
            "discriminator": {"propertyName": "action"},
        },
        "properties": {
            "action": {
                "type": "string",
                "enum": ["create", "generate", "retrieve", "retrieve_batch", "delete"],
            },
            "name": {"type": "string", "minLength": 1, "maxLength": 100},
            "audio_urls": {
                "type": "array",
                "minItems": 6,
                "maxItems": 24,
                "uniqueItems": True,
                "items": {"type": "string", "format": "uri", "pattern": "^https://"},
            },
            "callback_url": {"type": "string", "format": "uri", "pattern": "^https://"},
            "id": {"type": "string", "format": "uuid"},
            "lyric": {"type": "string"},
            "lyric_prompt": {"type": "string"},
            "style": {"type": "string"},
            "negative_tags": {"type": "string"},
            "title": {"type": "string"},
            "instrumental": {"type": "boolean"},
            "vocal_gender": {"type": "string", "enum": ["f", "m"]},
            "weirdness": {"type": "number", "minimum": 0, "maximum": 1},
            "style_influence": {"type": "number", "minimum": 0, "maximum": 1},
            "duration": {"type": "integer"},
            "async": {"type": "boolean"},
            "limit": {"type": "integer", "minimum": 1, "maximum": 100},
            "offset": {"type": "integer", "minimum": 0},
            "status": {
                "type": "string",
                "enum": ["queued", "uploading", "training", "ready", "failed", "archived"],
            },
        },
        "parameters": [
            {
                "name": "Idempotency-Key",
                "in": "header",
                "required": False,
                "schema": {"type": "string", "minLength": 1, "maxLength": 128},
            }
        ],
        "defaults": {"action": "retrieve_batch"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch"],
        "media_response": False,
    },
    "suno_projects": {
        "method": "POST",
        "path": "/suno/projects",
        "operation": "request",
        "schema": {
            "oneOf": [
                {
                    "type": "object",
                    "required": ["action", "title"],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["create"]},
                        "title": {"type": "string", "minLength": 1, "maxLength": 200},
                    },
                },
                {
                    "type": "object",
                    "required": ["action", "id"],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["retrieve"]},
                        "id": {"type": "string"},
                    },
                },
                {
                    "type": "object",
                    "required": ["action", "id", "state"],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["save"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "title": {"type": "string"},
                        "state": {"type": "object", "additionalProperties": True},
                    },
                },
                {
                    "type": "object",
                    "required": ["action", "id", "version_id", "audio_url"],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["upload"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "audio_url": {"type": "string", "pattern": "^https://"},
                        "async": {"type": "boolean"},
                        "callback_url": {"type": "string", "format": "uri"},
                    },
                },
                {
                    "type": "object",
                    "required": ["action", "id", "version_id", "audio_id"],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["add_track"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "audio_id": {"type": "string"},
                        "name": {"type": "string"},
                        "start_beats": {"type": "number", "minimum": 0},
                        "end_beats": {"type": "number", "minimum": 0},
                        "gain": {"type": "number"},
                    },
                },
                {
                    "type": "object",
                    "required": [
                        "action",
                        "id",
                        "version_id",
                        "source_audio_id",
                        "render_audio_id",
                        "stem_control_tags",
                        "model",
                        "start_seconds",
                        "end_seconds",
                    ],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["generate_track"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "source_audio_id": {"type": "string"},
                        "model": {
                            "type": "string",
                            "enum": [
                                "chirp-v3-5",
                                "chirp-v4",
                                "chirp-v4-5",
                                "chirp-v4-5-plus",
                                "chirp-v5",
                                "chirp-v5-5",
                                "chirp-v6",
                                "chirp-v6-wild",
                                "chirp-v6-mini",
                            ],
                        },
                        "title": {"type": "string"},
                        "tags": {"type": "string"},
                        "prompt": {"type": "string"},
                        "start_seconds": {"type": "number", "minimum": 0},
                        "end_seconds": {"type": "number", "exclusiveMinimum": 0},
                        "async": {"type": "boolean"},
                        "callback_url": {"type": "string", "format": "uri"},
                        "render_audio_id": {"type": "string"},
                        "stem_control_tags": {"type": "string"},
                        "batch_size": {"type": "integer", "minimum": 1, "maximum": 4},
                    },
                },
                {
                    "type": "object",
                    "required": [
                        "action",
                        "id",
                        "version_id",
                        "source_audio_id",
                        "model",
                        "start_seconds",
                        "end_seconds",
                    ],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["replace_section"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "source_audio_id": {"type": "string"},
                        "model": {
                            "type": "string",
                            "enum": [
                                "chirp-v3-5",
                                "chirp-v4",
                                "chirp-v4-5",
                                "chirp-v4-5-plus",
                                "chirp-v5",
                                "chirp-v5-5",
                                "chirp-v6",
                                "chirp-v6-wild",
                                "chirp-v6-mini",
                            ],
                        },
                        "title": {"type": "string"},
                        "tags": {"type": "string"},
                        "prompt": {"type": "string"},
                        "start_seconds": {"type": "number", "minimum": 0},
                        "end_seconds": {"type": "number", "exclusiveMinimum": 0},
                        "async": {"type": "boolean"},
                        "callback_url": {"type": "string", "format": "uri"},
                        "replacement_lyrics": {"type": "string"},
                        "fixed": {"type": "boolean"},
                    },
                },
                {
                    "type": "object",
                    "required": [
                        "action",
                        "id",
                        "version_id",
                        "operation_id",
                        "candidate_id",
                        "track_id",
                    ],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["commit_candidate"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "operation_id": {"type": "string"},
                        "candidate_id": {"type": "string"},
                        "track_id": {"type": "string"},
                        "start_beats": {"type": "number", "minimum": 0},
                        "end_beats": {"type": "number", "minimum": 0},
                        "async": {"type": "boolean"},
                        "callback_url": {"type": "string", "format": "uri"},
                    },
                },
                {
                    "type": "object",
                    "required": ["action", "id", "version_id", "track_id"],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["remove_track"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "track_id": {"type": "string"},
                    },
                },
                {
                    "type": "object",
                    "required": ["action", "id", "version_id", "title"],
                    "additionalProperties": False,
                    "properties": {
                        "action": {"type": "string", "enum": ["render"]},
                        "id": {"type": "string"},
                        "version_id": {"type": "string"},
                        "title": {"type": "string"},
                        "lyrics": {"type": "string"},
                        "tags": {"type": "string"},
                        "start_beats": {"type": "number", "minimum": 0},
                        "end_beats": {"type": "number", "minimum": 0},
                        "async": {"type": "boolean"},
                        "callback_url": {"type": "string", "format": "uri"},
                    },
                },
            ],
            "discriminator": {"propertyName": "action"},
        },
        "properties": {
            "action": {
                "type": "string",
                "enum": [
                    "create",
                    "retrieve",
                    "save",
                    "upload",
                    "add_track",
                    "generate_track",
                    "replace_section",
                    "commit_candidate",
                    "remove_track",
                    "render",
                ],
            },
            "title": {"type": "string", "minLength": 1, "maxLength": 200},
            "id": {"type": "string"},
            "version_id": {"type": "string"},
            "state": {"type": "object", "additionalProperties": True},
            "audio_url": {"type": "string", "pattern": "^https://"},
            "async": {"type": "boolean"},
            "callback_url": {"type": "string", "format": "uri"},
            "audio_id": {"type": "string"},
            "name": {"type": "string"},
            "start_beats": {"type": "number", "minimum": 0},
            "end_beats": {"type": "number", "minimum": 0},
            "gain": {"type": "number"},
            "source_audio_id": {"type": "string"},
            "model": {
                "type": "string",
                "enum": [
                    "chirp-v3-5",
                    "chirp-v4",
                    "chirp-v4-5",
                    "chirp-v4-5-plus",
                    "chirp-v5",
                    "chirp-v5-5",
                    "chirp-v6",
                    "chirp-v6-wild",
                    "chirp-v6-mini",
                ],
            },
            "tags": {"type": "string"},
            "prompt": {"type": "string"},
            "start_seconds": {"type": "number", "minimum": 0},
            "end_seconds": {"type": "number", "exclusiveMinimum": 0},
            "render_audio_id": {"type": "string"},
            "stem_control_tags": {"type": "string"},
            "batch_size": {"type": "integer", "minimum": 1, "maximum": 4},
            "replacement_lyrics": {"type": "string"},
            "fixed": {"type": "boolean"},
            "operation_id": {"type": "string"},
            "candidate_id": {"type": "string"},
            "track_id": {"type": "string"},
            "lyrics": {"type": "string"},
        },
        "parameters": [
            {
                "name": "Idempotency-Key",
                "in": "header",
                "required": False,
                "schema": {"type": "string", "minLength": 1, "maxLength": 128},
            }
        ],
        "defaults": {"action": "retrieve"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "suno_task_retrieve": {
        "method": "POST",
        "path": "/suno/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "suno_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/suno/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
            "required": ["action", "ids"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
